name: Project CI

on: 
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check python
        run: python --version
      
      - name: List Project Files
        run: ls -la
        
      - name: Run basic check
        run: echo "Project checks passed"